angular.module('cc')
  .config(function($stateProvider){
  	$stateProvider
  	  .state('message',{
  	  	url:'/message',
  	  	templateUrl:'app/message/message.html',
  	  	controller:'MessageController'
  	  })
  })